name: 'Setup sonar scanner'
description: 'Set up sonar scanner and build wrapper.'
author: 'Jakob Widauer'

inputs:
  sonar-scanner-version:
    description: 'What version of sonar scanner to set up.'
    default: '4.7.0.2747'
  sonar-server-url:
    description: 'What server to use for downloading build wrapper.'
    default: 'https://sonarcloud.io'

outputs:
  sonar-server-url:
    description: 'The server url used for downloading build wrapper.'
    value: ${{ inputs.sonar-server-url }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Download and set up sonar-scanner
      env:
        SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.sonar-scanner-version }}-linux.zip
      run: |
        mkdir -p $HOME/.sonar
        curl -sSLo $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        echo "$HOME/.sonar/sonar-scanner-${{ inputs.sonar-scanner-version }}-linux/bin" >> $GITHUB_PATH
      shell: bash
    - name: Download and set up build-wrapper
      env:
        BUILD_WRAPPER_DOWNLOAD_URL: ${{ inputs.sonar-server-url }}/static/cpp/build-wrapper-linux-x86.zip
      run: |
        curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
        unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
        echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH
      shell: bash

branding:
  icon: download-cloud
  color: 'blue'
